contrib/rpm/environment-modules.spec

contrib/rpm/environment-modules.spec: Now Obsoletes: modules-tcl. Results in modules-tcl being removed by yum when environment-modules is installed.

Add Obsoletes: modules-tcl to environment-modules.spec

---

modulecmd.tcl.in
testsuite/modules.70-maint/040-list.exp

Bug correction of the list command for the case when
the terminal width is equal to the text width to be printed
when only a single column is used.
Without the correction, the 'moudule list' command hangs.

Fix hanging 'list' command

---

MIGRATING.rst
NEWS.rst
doc/source/diff_v3_v4.rst
doc/source/module.rst
modulecmd.tcl.in
testsuite/example/siteconfig.tcl-2
testsuite/install.00-init/010-environ.exp
testsuite/modules.00-init/010-environ.exp
testsuite/modules.00-init/100-pager.exp
testsuite/modules.00-init/120-siteconfig.exp
testsuite/modules.00-init/150-access-init.exp

Adding MODULES_SITECONFIG env. variable support

---

NEWS.rst
doc/example/test-modulefiles/modulefiles/test_dir_and_file
doc/source/cookbook/test-modulefiles.rst

Add cookbook for ModulesTest.

---

README.md

Inside a code block URLs are not converted to links when the Markdown is rendered as HTML. In a quote they do. The other differences are minor both for the raw text and for the rendered text.

Use quote instead of code for links

---

doc/example/modulepaths-persist-over-sudo/rc
doc/example/test-modulefiles/modulefiles/test_dir_and_file
doc/source/conf.py
doc/source/cookbook/ensure-user-qualify-modules.rst
doc/source/cookbook/inhibit-report-info.rst
doc/source/cookbook/log-module-commands.rst
doc/source/cookbook/module-info-name-return-basename.rst
doc/source/cookbook/modulepaths-persist-over-sudo.rst
doc/source/cookbook/test-modulefiles.rst
doc/source/cookbook/unload-firstly-loaded.rst
doc/source/diff_v3_v4.rst
doc/source/module.rst
doc/source/modulefile.rst

For hyperlinks (in addition to using what Sphinx offers by default) I defined new directives/roles that can be used as ``.. subcmd::`` and ``:subcmd:`` (for the subcommands used for the modules command), and ``.. subcmdfile::`` and ``:subcmdfile:`` (for the subcommands used in modulefile).
I had to separate them in order to not get wrong links because they often have the same name but two different locations where they are documented.
I introduced usage of the ``.. versionadded::`` and  ``.. versionchanged::`` directives.
Some typos and grammar were also fixed.

Add hyperlinks to docs via semantic markup.

---

modulecmd.tcl.in
testsuite/modules.00-init/006-procs.exp

Since this variable is always rendered it might be evaluated in a strict scope and fail with the following error: `Global symbol "$_mlstatus" requires explicit package name (did you forget to declare "my $_mlstatus"?)`

Add "my" for perl's $_mlstatus

---

init/bash_completion.in

Hello,
Module 4 is a really good surprise, but I was disappointed to see that "ml" command had no bash completion.
All these fields are covered:
- every "module" options and commands;
- every "module load" options;
- every "module list" options;
- every loaded module with "-" suffix (ex: "-gcc" if "gcc" module is loaded).
Hope it helps!
Adrien

init/bash_completion.in: add 'ml' command support

---

init/bash_completion.in

Hello,
Just a little fix for ml bash_completion, add space between loaded modules.
Before: 
$ ml -<tab> <tab>
-intel-mpi
After:
$ ml -<tab> <tab>
-intel -mpi
Best,
Adrien

bash_completion: fix ml no space between -modules

---

modulecmd.tcl.in
testsuite/modules.00-init/150-access-init.exp

These changes result in no failed tests on macOS 10.15 as seen in #344, and might be useful for #304.

Use file normalise and load library using absolute path

---

doc/example/test-modulefiles/modulefiles/test_dir_and_file
doc/source/cookbook/test-modulefiles.rst

Use best practices: versioned magic cookie, ``getenv`` over ``$env``.
Add proper ReST references in doc.

Fix cookbook "Testing Modulefiles"

---

NEWS.rst
init/Makefile
init/bash_completion.in
init/tcsh_completion.in

This is done for tcsh and bash where those variables clutter the environment.
Closes #382

Replace completion helper vars with their content

---

MIGRATING.rst
NEWS.rst
doc/source/cookbook/sticky-modules.rst
doc/source/design/sticky-modules.rst
doc/source/design/variants.rst
doc/source/module.rst
tcl/modeval.tcl
tcl/subcmd.tcl.in
testsuite/modules.50-cmds/460-sticky.exp
testsuite/modules.50-cmds/461-super-sticky.exp
testsuite/modules.50-cmds/462-sticky-corner.exp
testsuite/modules.50-cmds/475-variant-tag.exp
testsuite/modules.61-coll/040-restore.exp

Fix stickiness typos

---

.aspell.en.pws
Makefile
NEWS.rst
lib/.gitignore
lib/Makefile.in
lib/envmodules.c
lib/testutil-sysconf.c
testsuite/example/siteconfig.tcl-1
testsuite/modules.00-init/005-init_ts.exp
testsuite/modules.00-init/120-siteconfig.exp

`sysconf` may fail to obtain the value of the `NGROUPS_MAX` variable.  In
such case, it returns -1 and sets `errno` to indicate the error.
Let's handle this situation as the size argument of `ckalloc` is an
`unsigned int` so the size of the allocated memory would be `UINT_MAX` instead.
Subsequently, `getgroups` would fail with `EINVAL` as `maxgroupsize` is non-zero
but less than the number of GIDs that would have been returned.
Note that if `sysconf` returns -1 and leaves `errno` intact, the given
variable has no limit.  However, that does not seem to be the case on
any reasonable operating system [1].
Found by Coverity.
Resolves:
```
modules-5.0.1/lib/envmodules.c:355: negative_return_fn: Function "sysconf(_SC_NGROUPS_MAX)" returns a negative number.
modules-5.0.1/lib/envmodules.c:355: …
```

lib: handle `sysconf` failure in `InitStateUsergroupsObjCmd`

---

.github/workflows/differential_shellcheck.yml

Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR.
I saw that your scripts are in great shape, but I think that you might find `differential-shellcheck` action useful. It is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to extend functionality.
/cc @lzaoral

ci(lint): add shell linter - Differential ShellCheck

---

INSTALL-win.rst
MIGRATING.rst
Makefile
NEWS.rst
README.md
configure
contrib/rpm/environment-modules.spec.in
doc/Makefile
doc/source/FAQ.rst
doc/source/changes.rst
doc/source/conf.py
doc/source/index.rst
doc/source/ml.rst
doc/source/module.rst
doc/source/modulefile.rst
testsuite/install.00-init/030-options.exp

modulefile man page is currently in the section 4 of man. According to `man man`, this is incorrect, as section 4 is for " Special files (usually found in /dev)". The man page for modulefile should be in section 5, "File formats and conventions, e.g. /etc/passwd".
This patch moves modulefile(4) to modulefile(5).
I hope that I didn't miss a place. Let me know if there is something that you want done differently.

modulefile man page moved from man4 to man5

---

.hunspell.en.dic
NEWS.rst
contrib/nagelfar/syntaxdb_modulefile.tcl
contrib/nagelfar/syntaxdb_modulerc.tcl
doc/source/changes.rst
doc/source/design/hide-or-forbid-modulefile.rst
doc/source/design/module-tags.rst
doc/source/modulefile.rst
tcl/mfcmd.tcl
testsuite/modulefiles.2/hide1/.modulerc
testsuite/modulefiles.3/tag/.modulerc
testsuite/modules.20-locate/112-hide-user-group.exp
testsuite/modules.20-locate/117-forbid-user-group.exp
testsuite/modules.50-cmds/440-module-tag.exp

Open PR to review code for explicit `user`/ `group` option in `module-{hide,forbid,tag}` command (see issue [here.](https://github.com/cea-hpc/modules/issues/520).
Code review needed to not use the boolean `flag`.

Issue#520 explicit user group for module hide forbid tag

---

init/Makefile
init/tcsh_completion.in

Add simple completion on "ml" command under tcsh.
This fix will allow to list unload module when user hit "tab" after "ml" command and will list loaded modules after "ml -"
All other completions (as for full "module" command) are not implemented to keep it simple

Add simple completion (loaded modules, avail modules) to "ml" command

---

tcl/mfcmd.tcl

Hi Xavier.  I am trying to understand how you implement module-hide.  As an Emacs user, the code highlighting sometimes get confused.  If I add  a # and a double quote on  certain lines, it clears up the syntax highlighting.  I checked to see if your .emacs  tcl-mode-hook fixed the issue and it does not.  Best, Robert.

Adding comment quotes so that Emacs syntax highlighting works

---

NEWS.rst
tcl/util.tcl
testsuite/config/base-config.exp
testsuite/install.00-init/020-module.exp
testsuite/install.00-init/024-ml.exp
testsuite/modulefiles/alias/3.0
testsuite/modules.50-cmds/076-alias-sub.exp

Square brackets may have special meaning on some shells (like csh), so they should be escaped.
Fixes #565

Escape `[` and `]` used in values within produced shell code

---

NEWS.rst
tcl/interp.tcl.in
testsuite/example/siteconfig.tcl-1
testsuite/modulefiles.3/interp/.modulerc
testsuite/modulefiles.3/interp/1
testsuite/modules.50-cmds/560-siteconfig-interp.exp

Fix interpreter variable reset between multiple modulefile or modulerc evaluations when variable initial value is an invalid list.
Fixes #570

Fix interp variable reset between evaluations
